# Generated by Django 4.1.5 on 2023-01-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_firname_profile_address_one_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
