# Generated by Django 4.1.5 on 2023-01-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
