# Generated by Django 4.1.5 on 2023-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clien_code', models.CharField(blank=True, max_length=200, null=True)),
                ('date_from', models.CharField(blank=True, max_length=200, null=True)),
                ('date_to', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_session', models.CharField(blank=True, max_length=200, null=True)),
                ('counselor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('counselor_Association', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor_Association', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('presenting_problem', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
