# Generated by Django 4.1.5 on 2023-01-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdetails',
            options={'verbose_name_plural': 'Client Details'},
        ),
        migrations.RenameField(
            model_name='clientdetails',
            old_name='clien_code',
            new_name='client_code',
        ),
    ]
