# Generated by Django 4.1.5 on 2023-01-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_clientdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='presenting_problem',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
