# Generated by Django 4.1.5 on 2023-01-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_clientdetails_presenting_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='counselor_Association_body',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='supervisor_Association_body',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
