# Generated by Django 4.1.5 on 2023-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_clientdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
